# Use phusion/baseimage as base image. To make your builds reproducible, make
# sure you lock down to a specific version, not to `latest`!
# See https://github.com/phusion/baseimage-docker/blob/master/Changelog.md for
# a list of version numbers.
FROM phusion/baseimage:<VERSION>

# Set correct environment variables.
ENV HOME /root

# Regenerate SSH host keys. baseimage-docker does not contain any, so you
# have to do that yourself. You may also comment out this instruction; the
# init system will auto-generate one during boot.
RUN /etc/my_init.d/00_regen_ssh_host_keys.sh

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

# ...put your own build instructions here...

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

MAINTAINER Alexander Kyxap <kyxap@pro-manage.net>

EXPOSE 22 80 1935

ADD dist/ /root/dist

# copy supervisor config
RUN cp /root/dist/nginx.supervisor.conf /etc/supervisor/conf.d/

RUN bash -x /root/dist/deploy.sh

# default start command
CMD ["/usr/bin/supervisord"]


